### ISSUE TITLE
Perform pitch tracking on companion app

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/PlayCompanion#3]
At the moment, mic data is sent uncompressed.

- Assuming 44100 Hz, it should be 44100 floats. Assuming 32bit floats, this would be 44100 * 4 bytes, which is approx. 175 KByte per second.
    - This is no problem for WLAN, but inefficient anyway.
    - There could be issues with many Companion Apps at the same time (this is still untested)

- One can check the network traffic using Windows Task-Manager.
    - I get approx. 520 KBit/s for the mic data of a single companion app running at 16000 Hz.
        - This is expected: 16000 floats, each having 32 bit results in 16000*32 = 512000 bit (64 KByte). Thus, Taks Manager tells truth :)

Better would be to sent compressed data. But only when compression and decompression are fast enough for proper real-time game play.

Question: which compression to use?
- Is there some ready-to-use audio (de)compression implementation for Unity (for all platforms)
- Is there a fast enough implementation of some (de)compression available as C# lib?

**Comment by basisbit** [comment]
instead of the audio, would it be possible to transmit the detected pitch plus a timestamp?

**Comment by achimmihca** [comment]
The part of the audio buffer that should be analyzed is currently determined on the main game, based on the BMP grid.
If the audio buffer is filled for one beat of the song, then the samples for this beat are analyzed.

The info which samples to analyze for which beat has to be synched with the companion app.
Then yes, the companion app can analyze the audio and only send the result.

**Comment by basisbit** [comment]
no need to transfer all the notes. Only tell the companion app the BPM, and then it can send a stream of every pitch per beat?

**Comment by achimmihca** [comment]
Yes, that's one option.
Of course this has to be synchronized with the audio playback (e.g. when paused). And the mic settings must be known (delay, amplification, noise suppression).
As alternative, the main game could request a set of beats from the companion app (c'app), thereby telling it which sample it should analyze.

Option (a) (aka. your suggestion)
- main game tells c'app to start recording. It sends BPM, mic settigns, position in song to c'app
    -  position in song is synched frequently (e.g. every second)
    - c'app should be able to find the required samples for a beat, analyze these, and send the result to the main game
    - c'app sends the pitch result every c'app-frame
- when the game is paused, the main game tells the c'app to pause

Option (b)
- main game tells c'app to analyze a list of sample ranges for certain beats,
    - main game sends this request every main-game-frame where there are new beats to be analyzed (mic buffer ready)
    - the main game knows already BPM, mic delay and position in song, such that it can determine all parameters for the c'app
    - c'app responds in the next c'app-frame

I think Option (a) is better because there is a constant stream of pitch results from the c'app.
This is probably better for latency and stability when compared to the request-response style of Option (b) .
