### ISSUE TITLE
Unity returns wrong value for max sample rate

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/PlayCompanion#5]
It tells me a max sample rate of 16 kHz for my Galaxy S10e, which supports 48 kHz.
You can find the sampe rate of your device using [this app](https://play.google.com/store/apps/details?id=br.com.vixti.samplerate)

There is a Unity [bug report](https://issuetracker.unity3d.com/issues/mobile-incorrect-values-returned-from-microphone-dot-getdevicecaps), which has been closed with no fix.
Screw you Unity!

So, we have to guess possible sample rates.
I suggest to provide a ComboBox with common values, i.e., 44100 Hz, 22050 Hz, 48000 Hz.
Default is 44100 Hz.

**Comment by basisbit** [comment]
Would instead just always using 44100Hz be an option? All devices should support that afaik

**Comment by achimmihca** [comment]
What brings you to this assumption?

I still would prefer to have the choice if higher sample rate results in better pitch tracking (may or may not be the case, not sure)

**Comment by achimmihca** [comment]
Sample rate is received from main game with https://github.com/UltraStar-Deluxe/PlayCompanion/commit/e7fff2692e3c8c906ba16c8a3e14a42e80165d59

I forgot to create a branch and pushed directly to master. You can check the commit for review if you want.

**Comment by basisbit** [comment]
looks good, thank you for this improvement!
