### ISSUE TITLE
Last release not compatible with ultrastar play 0.4

### ISSUE THREAD

**Issue by Goltergaul** [UltraStar-Deluxe/PlayCompanion#6]
Hi, thank You very much for this nice game. I noticed that the latest Release of the companion App is unfortunately not compatible with the latest game version

![Screenshot_20220401-135617](https://user-images.githubusercontent.com/34413/161258968-450e6d87-cf8e-4ae3-90a6-446becd5f1c3.jpg)

Or Do i Do something wrong?

**Comment by achimmihca** [comment]
You are right, the release of the Companion App was missing.
Please try https://github.com/UltraStar-Deluxe/PlayCompanion/releases/tag/v0.4.0

**Comment by achimmihca** [comment]
Thanks for the sponsorship ❤️ 
Will be re-invested purposefully 🚀

**Comment by Goltergaul** [comment]
awesome thanks :)
